### ISSUE TITLE
プログラミング言語の画像問題のリメイク + 難易度作成

### ISSUE THREAD

**Issue by mametakut** [yadokani389/IAmNotBunkei#13]

**Comment by yadokani389** [comment]
done in https://github.com/yadokani389/IAmNotBunkei/commit/2b9951b1118adaa5315c52f493fdd9e97070b7c6 https://github.com/yadokani389/IAmNotBunkei/commit/d5c3b2fa6ae242a7917bf6658a710fbec669980f
