### ISSUE TITLE
問題のレベル分け

### ISSUE THREAD

**Issue by mametakut** [yadokani389/IAmNotBunkei#15]
EASY : 中学生
NORMAL : 一般高専生
HARD : 時間かけたらいける、楽しめるぐらい
INSANE : キモイやつ

**Comment by SoumaCisar** [comment]
僕が今のところしてある難易度調整
Easy: 中2,3が解けるくらい
Normal: 高専1年が解けるくらい
Hard: 高専生2年以上が解けるくらい
Insane: もはや謎
