### ISSUE TITLE
残り時間の描画 & スコアの描画 & スコアの同期

### ISSUE THREAD

**Issue by mametakut** [yadokani389/IAmNotBunkei#22]

**Comment by yadokani389** [comment]
残り時間は上のプログレスバーですることにした https://github.com/yadokani389/IAmNotBunkei/commit/199c9a02b352725da454619a728690b0405fc006

**Comment by yadokani389** [comment]
ポイント同期 https://github.com/yadokani389/IAmNotBunkei/commit/d59daf42d28893d25ebb5dd3311c28d971e47f70
現在のポイント表記はしない
